function cellInfo = V2Xbusses(varargin) 
% V2XBUSSES returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'PRESCAN_V2X_USER_GENERIC_DATA', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'messageID', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'senderID', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'signal_1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'signal_4', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'signal_5', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'discrete_signal_3', 1, 'int32', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'PRESCAN_V2X_USER_GENERIC_MESSAGE', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'HEADER', 1, 'Bus: PRESCAN_HEADER', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DATA', 1, 'Bus: PRESCAN_V2X_USER_GENERIC_DATA', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
